language: objective-c
osx_image: xcode9

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild -workspace BoilerplateWars.xcworkspace -scheme 'BoilerplateWars' -destination 'platform=iOS Simulator,name=iPhone 6' build test CODE_SIGN_IDENTITY=- | xcpretty -c
